### ISSUE TITLE
How to use in combination with nexus-plugin-prisma?

### ISSUE THREAD

**Issue by maaft** [lvauvillier/nexus-plugin-shield#5]
Hi, how can I use this shield-plugin in combination with the nexus-prisma-plugin to shield my generated CRUD operations? 

For now, my app.ts looks like this:
```typescript
import { use } from 'nexus'
import { prisma } from 'nexus-plugin-prisma'
import { PrismaClient } from 'nexus-plugin-prisma/client'
import { schema } from 'nexus'

import { shield, rule, deny, not, and, or } from 'nexus-plugin-shield'

const isAuthenticated = rule({ cache: 'strict' })(
  async (parent, args, ctx: NexusContext, info) => {
    // only have access to ctx.db, therefore I tried with parent.id
    // parent is "undefined" --> Where does ctx.user come from?
    return ctx.db.user.findOne({where: {id: parent.id}}) !== null
  }
)

const permissions = shield({
  rules: {
    Query: {
      posts: isAuthenticated
    },
    Mutations: {

    },
  },
  options: {
    fallbackRule: deny,
  },
})

use(permissions)

use(prisma({
    client: { instance: new PrismaClient() },
    features: {crud: true}
  }))

schema.queryType({
  definition(t) {
    t.crud.posts()  // I want to guard this query
   // ...
  }
})
```

**Comment by lvauvillier** [comment]
Hi @maaft,

`parent` arg refers to parent node in the graphql resolution process.

In your case, when isAuthenticated is applied to protect the `posts` query, the `parent` arg refers to the root `Query` Node (and has no id).

Can you explain what is the logic you want to implement here ?

**Comment by lvauvillier** [comment]
This is an example to implement an isAuthenticated rule based on token authentication :

```
schema.addToContext((req) => {
  return {
    token: validateAndExtractTokenInfoFromRequestHeader(req)
  };
});

const isAuthenticated = rule({ cache: 'strict' })(
  async (parent, args, ctx: NexusContext, info) => {
  const user = await ctx.db.user.findOne({where: {id: ctx.token.userid}});
  // check what you want here (permissions, access etc...) and return true or throw an error.
  }
)
```

**Comment by maaft** [comment]
Thank you very much!

I got my signup/login authentication working so far.

In a next step I want to check ownership for certain data models. Therefore I added a "owner" field to to objects which I want to protect.

Because you can also attach rules to object types, I tried added a checkOwnership rule to my `Project` type. Unfortunately when I now query all projects, I get an authorization error. When I use the `filter` option to return only **my** projects instead, the query goes through successfully.
As I find the enforcement of filtering to every query a little bit awkward, is there any option for graphql-shield to return only successful leaf results? Or is there a better way to enforce ownership?


```typescript
const ownsProject = rule({cache: 'contextual'})(
  async ({ id }, args, ctx: NexusContext, info) => {
    const userId = getUserId(ctx)
    const project = await ctx.db.project.findOne({where: {id: id}})
    
    if (Boolean(project)) {
        console.log(project?.owner)
        console.log(userId)
        return project?.owner === userId
    }

    return false
  }
)

const permissions = shield({
  rules: {
    Query: {
      "*": isAuthenticated
    },
    Mutations: {
      "*": isAuthenticated,
      login: allow,
      signup: allow
    },
    Project: and(ownsProject, isAuthenticated)
  },
  options: {
    fallbackRule: allow,
  },
})
```

Thank you very much in advance!

And as you seem to be involved a bit in the nexus framework ecosystem, is there any forum or similar where beginners like me can ask questions that are not covered in the official documentation yet?

**Comment by maaft** [comment]
Also, is there any other way to check for existence in the database? With my current implementation I will ask the database twice for each query:

1.) Check ownership: `db.project.findOne(...)`
2.) Resolver: `db.project.findOne(...)`

**Comment by lvauvillier** [comment]
Unfortunately you cannot avoid multiple queries. This is why cache is important if you have to use multiple times the same rule.

To avoid multiple queries you can just check the token and enforce `where` filters in your resolvers.

```typescript
const permissions = shield({
  rules: {
    Query: {
      "projects": isAuthenticated
    },
    Mutations: {
      "*": isAuthenticated,
      login: allow,
      signup: allow
    },
  },
  options: {
    fallbackRule: allow,
  },
})

schema.extendType({
  type: "Query",
  definition(t) {
    t.crud.projects({
      filtering: true,
      resolve: async (root, { where, ...args }, ctx, info, originalResolve) => {
        return await originalResolve(
          root,
          {
            ...args,
            where: {
              ...where,
                users: {
                some: {
                  id: ctx.token.userId
                }
              }
            }
          },
          ctx,
          info
        );
      }
    });
  }
});
```

**Comment by lvauvillier** [comment]
I close the issue and invite you to discuss implement details on SO, slack or nexus discussions.
